### ISSUE TITLE
Hyperlinks?

### ISSUE THREAD

**Issue by HDVinnie** [HDVinnie/Private-Trackers-Spreadsheet#52]
Have site name contain hyperlink too site?

**Comment by nafanz** [comment]
On the one hand, it would be convenient, but I'm sure that tracker admins will react to this positively. Since some resources prohibit publishing the full names of trackers and their addresses.

**Comment by nafanz** [comment]
@HDVinnie on the other hand, if hyperlinks make it possible to obtain `Mozilla Observatory` status dynamically and not store it in `json`, this may be a plus. Since many users are most likely not in the know about this service and will not add data to this column. I myself snuck about him just now.

In the future, you can still get the status of `open registration` (if it is, of course, possible to implement).

**Comment by refriedfood** [comment]
Every bit of information I added to it has disappeared... nice.

**Comment by HDVinnie** [comment]
@refriedfood you sure about that? look like you have changes in your fork. patch-1 branch that you never made a PR with.

**Comment by refriedfood** [comment]
I don't want to do it now for fear of overwriting, since there have been changes. I'm not exacty sure how to update this info now/contribute.
