### ISSUE TITLE
Codebase \ Torrent Tracker Platforms

### ISSUE THREAD

**Issue by nafanz** [HDVinnie/Private-Trackers-Spreadsheet#78]
I propose to transfer information from this [repository](https://github.com/HDVinnie/Torrent-Tracker-Platforms) to the main table (to a separate tab).
Receive information via API, for example:
https://api.github.com/repos/OPSnet/Gazelle

**Comment by HDVinnie** [comment]
Good idea. Im currently busy with UNIT3D at the moment but can look into it soon unless you plan to make a PR?

**Comment by nafanz** [comment]
I tried to figure it out, but my knowledge was not enough.

**Comment by nafanz** [comment]
I would use these fields:
* full_name
* description
* archived
* watchers
* forks
* contributors - https://api.github.com/repos/OPSnet/Gazelle/contributors
* languages - https://api.github.com/repos/OPSnet/Gazelle/languages

@HDVinnie maybe you have time or @tracker-user may I help.

**Comment by another-acc** [comment]
@nafanz @HDVinnie I'll see what I can do.

Unfortunately GitHub flagged my @tracker-user account so all the issues and pull requests I created are now hidden.
I created a support ticket, hopefully they'll resolve it, .

Probably got a false positive because I mentioned ~200 tracker names in another issue (wrote a big comment).
I'll get back to you once my main account is available again.

**Comment by nafanz** [comment]
Sad :(
